"""The palette: the tokens, the two themes, and the switch between them.

The theme is module-level mutable state, which is exactly the shape of thing
that is easy to get subtly wrong: a token that only one palette defines, a
subscriber that is called on a deleted widget, a preference that is remembered
as "whatever the desktop happened to be".  Each of those is pinned here.

Every test that moves the theme puts it back, through the fixture below, so the
rest of the suite keeps running against the console's default.
"""

from __future__ import annotations

import dataclasses
import re

import pytest

from litegrip_studio.settings import KEY_THEME, Settings
from litegrip_studio.ui import theme
from litegrip_studio.ui.widgets import Banner, StatusDot


def _rules(sheet: str) -> list[tuple[str, str]]:
    """Split a stylesheet into ``(selectors, declarations)`` pairs.

    Enough of a parser for the one question the tests ask of the sheet — what a
    given selector is given.  The sheet is generated by this repository and has
    no nested at-rules, so a scan for ``{`` and the matching ``}`` is the whole
    of it.
    """
    rules: list[tuple[str, str]] = []
    # Comments first: a banner comment sits between the previous rule and the
    # next selector, and would otherwise be read as part of that selector.
    for chunk in re.sub(r"/\*.*?\*/", "", sheet, flags=re.S).split("}"):
        if "{" not in chunk:
            continue
        selectors, declarations = chunk.split("{", 1)
        rules.append((" ".join(selectors.split()), declarations))
    return rules


@pytest.fixture(autouse=True)
def restore_theme():
    """Put the console back on its default palette after every test here."""
    before = theme.current_theme()
    yield
    theme.set_theme(before)


class TestTheTokens:
    def test_both_palettes_define_every_token(self) -> None:
        """A token added to one theme and forgotten in the other is a colour
        that silently goes missing, so the two field lists are compared."""
        dark = {f.name for f in dataclasses.fields(theme.PALETTES[theme.DARK])}
        light = {f.name for f in dataclasses.fields(theme.PALETTES[theme.LIGHT])}

        assert dark == light
        assert dark - {"name", "label"}, "a palette with no colours is not a palette"

    @pytest.mark.parametrize("name", [theme.DARK, theme.LIGHT])
    def test_every_colour_is_a_colour(self, name: str) -> None:
        palette = theme.PALETTES[name]

        for field in dataclasses.fields(palette):
            value = getattr(palette, field.name)
            if field.name in ("name", "label"):
                continue
            assert value.startswith("#") or value.startswith("rgba("), field.name

    def test_the_two_themes_are_not_the_same_theme(self) -> None:
        """The whole point of a pair is that the surfaces invert."""
        dark, light = theme.PALETTES[theme.DARK], theme.PALETTES[theme.LIGHT]

        assert dark.background != light.background
        assert dark.text != light.text
        assert dark.panel != light.panel

    @pytest.mark.parametrize("name", [theme.DARK, theme.LIGHT])
    def test_the_measured_green_is_the_success_green(self, name: str) -> None:
        """One green means "the jaws are here", in the slider, the readout and
        the plot.  Held in both themes, not just the default one."""
        theme.set_theme(name)

        assert theme.ACTUAL == theme.OK
        assert theme.ACTUAL != theme.TARGET, "the command is not the measurement"

    @pytest.mark.parametrize("name", [theme.DARK, theme.LIGHT])
    def test_every_severity_has_a_text_fill_and_edge(self, name: str) -> None:
        theme.set_theme(name)

        for severity in ("ok", "info", "warn", "error"):
            text, fill, edge = theme.severity_colours(severity)
            assert text.startswith("#")
            assert fill.startswith("#") or fill.startswith("rgba(")
            assert edge.startswith("#")
            assert len({text, fill, edge}) == 3, "a wash that equals its own text"

    def test_an_unknown_severity_is_muted_rather_than_alarming(self) -> None:
        assert theme.severity_colours("plaid") == (
            theme.TEXT,
            theme.PANEL_ALT,
            theme.BORDER,
        )

    def test_muted_ink_is_the_secondary_ink(self) -> None:
        assert theme.ink("muted") == theme.TEXT_MUTED
        assert theme.ink("error") == theme.ERROR


class TestTheSwitch:
    def test_it_moves_the_tokens_not_just_the_name(self) -> None:
        theme.set_theme(theme.DARK)
        dark = (theme.BACKGROUND, theme.PANEL, theme.TEXT, theme.ERROR)

        theme.set_theme(theme.LIGHT)

        assert theme.current_theme() == theme.LIGHT
        assert (theme.BACKGROUND, theme.PANEL, theme.TEXT, theme.ERROR) != dark

    def test_toggling_goes_back_and_forth(self) -> None:
        theme.set_theme(theme.DARK)

        assert theme.toggle_theme() == theme.LIGHT
        assert theme.toggle_theme() == theme.DARK

    def test_an_unknown_name_is_ignored_rather_than_fatal(self) -> None:
        """The theme is a preference, and a preferences file edited by hand
        must not be able to stop the console from opening."""
        theme.set_theme(theme.DARK)

        assert theme.set_theme("plaid") == theme.DARK
        assert theme.current_theme() == theme.DARK

    def test_setting_the_theme_it_is_already_on_changes_nothing(self) -> None:
        theme.set_theme(theme.DARK)
        palette = theme.PANEL

        assert theme.set_theme(theme.DARK) == theme.DARK
        assert theme.PANEL == palette

    def test_an_unset_preference_is_the_console_s_own_default(self) -> None:
        """Not "whatever the desktop is": the console opened dark before there
        was a choice and still does, so nothing changes out of the box."""
        assert theme.resolve(None) == theme.DEFAULT_THEME

    def test_a_stored_preference_is_honoured(self) -> None:
        assert theme.resolve(theme.LIGHT) == theme.LIGHT
        assert theme.resolve(theme.DARK) == theme.DARK

    def test_a_nonsense_preference_falls_back_to_the_default(self) -> None:
        """A hand-edited preferences file must not be able to leave the console
        with no palette, nor with an arbitrary half of the pair."""
        assert theme.resolve("plaid") == theme.DEFAULT_THEME


class TestTheSubscribers:
    def test_a_subscriber_is_told_and_can_stop_listening(self) -> None:
        heard: list[str] = []
        unsubscribe = theme.subscribe(lambda: heard.append(theme.current_theme()))
        theme.set_theme(theme.DARK)

        theme.set_theme(theme.LIGHT)
        assert heard == [theme.LIGHT]

        unsubscribe()
        theme.set_theme(theme.DARK)
        assert heard == [theme.LIGHT], "an unsubscribed listener was still called"

    def test_a_subscriber_whose_owner_has_gone_is_dropped(self, qapp) -> None:
        """Held weakly, because a window outliving the widget it subscribed is
        the normal case in a test suite and the abnormal case in a session."""
        dot = StatusDot("ok", "已连接")
        theme.set_theme(theme.DARK)
        del dot

        # Would raise RuntimeError if the dead bound method were still held.
        theme.set_theme(theme.LIGHT)

        assert theme.current_theme() == theme.LIGHT

    def test_the_widgets_themselves_repaint(self, qapp) -> None:
        """The chips and the banners paint a colour rather than asking for one,
        so a subscriber that is never called leaves them on the old palette —
        which is how this was found: only the tab content changed."""
        theme.set_theme(theme.DARK)
        dot = StatusDot("ok", "已连接")
        banner = Banner()
        banner.set("warn", "注意")
        dark_dot, dark_banner = dot.styleSheet(), banner.styleSheet()

        theme.set_theme(theme.LIGHT)

        assert dot.styleSheet() != dark_dot
        assert theme.PANEL_ALT in dot.styleSheet()
        assert banner.styleSheet() != dark_banner
        assert theme.WARN_SOFT in banner.styleSheet()

    def test_a_readout_that_has_never_had_a_number_repaints_too(self, qapp) -> None:
        """A readout colours *itself*, so it cannot be re-rendered from its own
        contents the way a banner can.  Held as a colour, the ordinary ink would
        be whichever palette the widget was built under — and the readouts that
        have not been given a number yet are exactly the ones with nothing to
        recover the colour from."""
        from litegrip_studio.ui.widgets import PositionReadout

        theme.set_theme(theme.DARK)
        readout = PositionReadout()
        assert theme.TEXT in readout.actual.text()

        theme.set_theme(theme.LIGHT)

        assert theme.TEXT in readout.actual.text()
        assert theme.PALETTES[theme.DARK].text not in readout.actual.text()

    def test_a_readout_showing_no_measurement_repaints_too(self, qapp) -> None:
        """The frame that carries nothing is still a frame: the em dash it draws
        is the measured colour, so it has to be redrawn when that colour moves.
        A guard that treated "no measurement" as "nothing rendered" left this
        one on the old palette."""
        from litegrip_studio.ui.widgets import UNKNOWN, PositionReadout

        theme.set_theme(theme.DARK)
        readout = PositionReadout()
        readout.update_position(None, None)
        assert readout.actual.value == UNKNOWN

        theme.set_theme(theme.LIGHT)

        assert theme.ACTUAL in readout.actual.text()
        assert theme.PALETTES[theme.DARK].actual not in readout.actual.text()


class TestTheStylesheet:
    @pytest.mark.parametrize("name", [theme.DARK, theme.LIGHT])
    def test_it_is_built_from_the_theme_in_force(self, name: str) -> None:
        theme.set_theme(name)

        sheet = theme.stylesheet()

        assert theme.PANEL in sheet
        assert theme.BACKGROUND in sheet
        assert "QGroupBox" in sheet
        assert "QTabBar::tab" in sheet

    def test_the_two_themes_produce_different_sheets(self) -> None:
        theme.set_theme(theme.DARK)
        dark = theme.stylesheet()
        theme.set_theme(theme.LIGHT)

        assert theme.stylesheet() != dark

    def test_it_does_not_paint_a_bare_widget(self) -> None:
        """A background on ``QWidget`` cascades to every label and every plain
        container, which is what put an inset rectangle behind each of them.
        The rule is still there for the type; it just carries no surface.

        Only a rule whose selector *is* ``QWidget`` counts — ``QScrollArea >
        QWidget > QWidget`` names a specific ancestor chain and is how the
        scroll area is made see-through.
        """
        exact = [
            (selectors, declarations)
            for selectors, declarations in _rules(theme.stylesheet())
            if any(part.strip() == "QWidget" for part in selectors.split(","))
        ]

        assert exact, "the type rule is what the whole sheet inherits from"
        for selectors, declarations in exact:
            assert "background" not in declarations, selectors

    def test_the_palette_reaches_the_application(self, qapp) -> None:
        """Native Qt chrome — a file chooser, a message box — reads the palette
        rather than the sheet, so the two have to be applied together."""
        from PyQt5.QtGui import QPalette

        theme.set_theme(theme.DARK)
        theme.apply(qapp)

        assert qapp.styleSheet() == theme.stylesheet()
        assert qapp.palette().color(QPalette.Window).name() == theme.BACKGROUND


class TestThePreference:
    def test_an_unchosen_theme_is_remembered_as_unchosen(self) -> None:
        """``None`` rather than the resolved name, so that "nobody has chosen"
        is still readable a restart later instead of being indistinguishable
        from a choice that happened to match the default."""
        assert Settings(_Store()).theme is None

    def test_a_chosen_theme_round_trips(self) -> None:
        store = _Store()
        settings = Settings(store)

        settings.theme = theme.LIGHT
        assert settings.theme == theme.LIGHT
        assert store.value(KEY_THEME) == theme.LIGHT

        settings.theme = None
        assert settings.theme is None
        assert store.value(KEY_THEME) is None

    def test_a_hand_edited_value_reads_as_unchosen(self) -> None:
        assert Settings(_Store(**{KEY_THEME: "plaid"})).theme is None


class _Store:
    """The dictionary-backed double the settings tests use."""

    def __init__(self, **initial) -> None:
        self.data = dict(initial)

    def value(self, key, default=None):
        return self.data.get(key, default)

    def setValue(self, key, value) -> None:
        self.data[key] = value

    def remove(self, key) -> None:
        self.data.pop(key, None)

    def sync(self) -> None:
        pass


class TestTheLogCard:
    """The dock stopped being a card for one revision, and nobody noticed until
    a reviewer asked where the panel had gone.

    The console draws its own log title bar — the style's cannot hold the debug
    filter — and replacing that title rule without replacing what it painted
    left the dock as the one flat region in the window.  So the surfaces are
    asserted, not assumed.
    """

    def test_the_header_and_the_body_carry_the_panel(self) -> None:
        rules = dict(_rules(theme.stylesheet()))

        for selector in ("#LogTitle", "#LogBody"):
            assert selector in rules, selector
            assert theme.PANEL in rules[selector]

    def test_the_two_halves_make_one_card(self) -> None:
        """Each draws three sides of the border; between them they must draw
        all four with no seam down the middle."""
        rules = dict(_rules(theme.stylesheet()))

        assert "border-bottom: none" in rules["#LogTitle"]
        assert "border-top: none" in rules["#LogBody"]
        assert "border-top-left-radius" in rules["#LogTitle"]
        assert "border-bottom-left-radius" in rules["#LogBody"]

    def test_the_state_line_has_no_strip(self) -> None:
        """A panel down here is cut off at both ends by the window's gutter —
        the top rule simply stops in mid-air — which is what made the footer
        look clipped.  The console's chrome is a bare row; its surfaces are the
        cards."""
        rules = dict(_rules(theme.stylesheet()))

        for selector in ("QStatusBar", "#StateLine"):
            assert "background: transparent" in rules[selector], selector
            assert "border: none" in rules[selector], selector
